services:
  telemetry-api:
    container_name: telemetry-api
    image: ghcr.io/pyrevitlabs/telemetry-server:latest
    build:
      context: .
      dockerfile: src/Telemetry.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
