// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telemetry.Api.Infrastructure.Persistence;

#nullable disable

namespace Telemetry.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402141622_AddCancellableSqlite")]
    partial class AddCancellableSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Telemetry.Api.Domain.Models.EventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool?>("Cancellable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cancellable");

                    b.Property<bool?>("Cancelled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cancelled");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("docid");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("docname");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("docpath");

                    b.Property<string>("DocumentTemplate")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("doctemplate");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("doctype");

                    b.Property<string>("EventArgs")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("args");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<Guid>("HandlerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("handler_id");

                    b.Property<string>("HostUsername")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("host_user");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("meta");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("projectname");

                    b.Property<string>("ProjectNum")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("projectnum");

                    b.Property<string>("RevitBuild")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("revitbuild");

                    b.Property<string>("RevitVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("revit");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("event_record", (string)null);
                });

            modelBuilder.Entity("Telemetry.Api.Domain.Models.ScriptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CloneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("clone");

                    b.Property<string>("CommandBundle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("commandbundle");

                    b.Property<string>("CommandExtension")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("commandextension");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("commandname");

                    b.Property<string>("CommandResults")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("commandresults");

                    b.Property<string>("CommandUniqueName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("commanduniquename");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("docname");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("docpath");

                    b.Property<string>("ExecId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("exec_id");

                    b.Property<DateTimeOffset>("ExecTimestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("exec_timestamp");

                    b.Property<string>("HostUsername")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("host_user");

                    b.Property<bool>("IsConfig")
                        .HasColumnType("INTEGER")
                        .HasColumnName("config");

                    b.Property<bool>("IsDebug")
                        .HasColumnType("INTEGER")
                        .HasColumnName("debug");

                    b.Property<bool>("IsExecFromGui")
                        .HasColumnType("INTEGER")
                        .HasColumnName("from_gui");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("meta");

                    b.Property<string>("PyRevitVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("pyrevit");

                    b.Property<int>("ResultCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resultcode");

                    b.Property<string>("RevitBuild")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("revitbuild");

                    b.Property<string>("RevitVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("revit");

                    b.Property<string>("ScriptPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("scriptpath");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("sessionid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("Trace")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trace");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("script_record", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
