// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Telemetry.Api.Infrastructure.Persistence;

#nullable disable

namespace Telemetry.Migrations.Postgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Telemetry.Api.Domain.Models.EventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("_id");

                    b.Property<bool?>("Cancellable")
                        .HasColumnType("boolean")
                        .HasColumnName("cancellable");

                    b.Property<bool?>("Cancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("cancelled");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("docid");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("docname");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("docpath");

                    b.Property<string>("DocumentTemplate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("doctemplate");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("doctype");

                    b.Property<string>("EventArgs")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("args");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<Guid>("HandlerId")
                        .HasColumnType("uuid")
                        .HasColumnName("handler_id");

                    b.Property<string>("HostUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("host_user");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("projectname");

                    b.Property<string>("ProjectNum")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("projectnum");

                    b.Property<string>("RevitBuild")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("revitbuild");

                    b.Property<string>("RevitVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("revit");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Telemetry.Api.Domain.Models.ScriptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("_id");

                    b.Property<string>("CloneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clone");

                    b.Property<string>("CommandBundle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("commandbundle");

                    b.Property<string>("CommandExtension")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("commandextension");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("commandname");

                    b.Property<string>("CommandResults")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("commandresults");

                    b.Property<string>("CommandUniqueName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("commanduniquename");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("docname");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("docpath");

                    b.Property<string>("ExecId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("exec_id");

                    b.Property<DateTimeOffset>("ExecTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exec_timestamp");

                    b.Property<string>("HostUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("host_user");

                    b.Property<bool>("IsConfig")
                        .HasColumnType("boolean")
                        .HasColumnName("config");

                    b.Property<bool>("IsDebug")
                        .HasColumnType("boolean")
                        .HasColumnName("debug");

                    b.Property<bool>("IsExecFromGui")
                        .HasColumnType("boolean")
                        .HasColumnName("from_gui");

                    b.Property<string>("PyRevitVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pyrevit");

                    b.Property<int>("ResultCode")
                        .HasColumnType("integer")
                        .HasColumnName("resultcode");

                    b.Property<string>("RevitBuild")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("revitbuild");

                    b.Property<string>("RevitVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("revit");

                    b.Property<string>("ScriptPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("scriptpath");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessionid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("scripts");
                });

            modelBuilder.Entity("Telemetry.Api.Domain.Models.ScriptRecord", b =>
                {
                    b.OwnsOne("Telemetry.Api.Domain.Models.TraceInfo", "Trace", b1 =>
                        {
                            b1.Property<Guid>("ScriptRecordId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(8000)
                                .HasColumnType("character varying(8000)")
                                .HasColumnName("message");

                            b1.HasKey("ScriptRecordId");

                            b1.ToTable("scripts");

                            b1.WithOwner()
                                .HasForeignKey("ScriptRecordId");

                            b1.OwnsOne("Telemetry.Api.Domain.Models.EngineInfo", "Engine", b2 =>
                                {
                                    b2.Property<Guid>("TraceInfoScriptRecordId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Configs")
                                        .HasMaxLength(8000)
                                        .HasColumnType("jsonb")
                                        .HasColumnName("configs");

                                    b2.PrimitiveCollection<string[]>("SysPaths")
                                        .HasColumnType("text[]")
                                        .HasColumnName("syspath");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("type");

                                    b2.Property<string>("Version")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("version");

                                    b2.HasKey("TraceInfoScriptRecordId");

                                    b2.ToTable("scripts");

                                    b2.WithOwner()
                                        .HasForeignKey("TraceInfoScriptRecordId");
                                });

                            b1.Navigation("Engine")
                                .IsRequired();
                        });

                    b.Navigation("Trace")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
